server:
  port: 8080
  servlet:
    context-path: /fate

spring:
  datasource:
    #  数据源基本配置
    username: root
    password: 123456
    url: jdbc:mysql://124.71.190.211:3306/fate?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    # url: jdbc:mysql://localhost:3306/fate?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB

file:
  staticAccessPath: /upload/**
  uploadFolder: /root/upload/

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
    # configuration:
  # map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

site:
  # 配置跨域域名
  corsDomain: ["https://www.tuzixinwen.com","https://m.tuzixinwen.com","http://localhost:3000","http://localhost:3001"]
  # 每页显示条数
#  pageSize: 20
#  createTopicScore: 10
#  goodTopicScore: 20
#  createCommentScore: 5
  # 下面是配置管理员，配置在后面的名字的用户都是管理员
  admin: []
  # 下面是被ban的用户，被ban后，不能发布话题和评论
  ban: []

# jwt相关配置，保持默认就可以了
jwt:
  header: "Authorization"
  secret: "mySecret"
  expiration: 3600 # 1小时有效期 单位 s
  allow_exp: 604800 # 7天保质期 单位 s
  tokenHead: "Bearer "